<?php
/**
 * Space48_FeeshippingPromo
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0), a
 * copy of which is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Space48
 * @package    Space48_FeeshippingPromo
 * @author     Space48 <hello@space48.com>
 * @copyright  Copyright (c) 2012 Space 48 LTD.
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<?php $limits = Mage::getModel('freeshippingpromo/freeshippingpromo')->getLimits(); ?>
<?php if( ($limits['lowerLimit'] < $limits['cartTotal']) && ($limits['cartTotal'] < $limits['upperLimit']) ): ?>
	<div id="cart-freeshipping-promo">
	<?php $spend = Mage::helper('core')->currency(($limits['upperLimit'] - $limits['cartTotal']), true, false); ?>
		<i class="icon delivery"></i><?php echo $this->__('Spend %1$s more to get Free UK Delivery',$spend); ?>
	</div>
<?php endif; ?>