<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>

<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): // has images ?>
    <div id="product-gallery" class="product-image">
        <div class="zoom-btn" title="Click to Zoom">Zoom</div>

        <?php $count = 0; foreach ($this->getGalleryImages() as $_image): $count++; ?>
            <img class="image" id="img-<?php echo $count ?>" src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize(300); ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />
            <a id="link-img-<?php echo $count ?>" href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()); ?>" class="zoom"></a>
        <?php endforeach; ?>
    </div>
<?php else: // no image/placeholder ?>
    <div id="product-gallery" class="product-image">
        <img id="image" src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image'); ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
    </div>
<?php endif; ?>

<?php if (count($this->getGalleryImages()) > 0): // "more views" ?>
    <div class="more-views">
<!--        <div class="center">-->
        <?php $count = 0; foreach ($this->getGalleryImages() as $_image): $count++; ?>
            <a href="#" rel="img-<?php echo $count ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>">
                <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(70); ?>" width="70" height="70" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />
            </a>
        <?php endforeach; ?>
<!--        </div>-->
    </div>
<?php endif; ?>
