<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<h2 class="subtitle"><?php echo $this->__('Featured Products') ?></h2>
<?php $_columnCount = $this->getColumnCount(); ?>
    <?php $i=0; foreach ($_products->getItems() as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135) ?>" width="135" height="135" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /></a>
                <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h3>
                
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                
                <?php echo $this->getPriceHtml($_product, true, '-new') ?>
                
				<?php if ($this->helper('wishlist')->isAllow()) : ?>
                    <a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a>
                <?php endif; ?>
                <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                    <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Compare') ?></a>
                <?php endif; ?>

                <div class="short-description">
                    <div class="std"><?php echo nl2br($_product->getShortDescription()) ?></div>
                </div>

				<div class="compatibility">
				<?php if ($_product->getCompatibility()): ?>

					<?php if ($_product->getAttributeText('compatibility') == 'Windows 7 Included'): ?>
                        <span class="windows"></span><p><?php echo $_product->getAttributeText('compatibility') ?></p>
                    <?php endif; ?>
                    
                    <?php if ($_product->getAttributeText('compatibility') == 'OSX Lion Included'): ?>
                        <span class="osx"></span><p><?php echo $_product->getAttributeText('compatibility') ?></p>
                    <?php endif; ?>
                    
                    <?php if ($_product->getAttributeText('compatibility') == 'PC &amp; Mac Compatible'): ?>
                        <span class="windows"></span><span class="osx"></span><p><?php echo $_product->getAttributeText('compatibility') ?></p>
                    <?php endif; ?>

                <?php endif; ?>
                </div>
                
                
                
                <div class="actions">
                    <?php if($_product->isSaleable()): ?>
                    	<a class="small-buy-btn" href="<?php echo $_product->getProductUrl() ?>"  title="<?php echo $this->htmlEscape($_product->getName()) ?>">BUY NOW <span>Read More</span></a>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                </div>
            </li>
        <?php if ($i%$_columnCount==0 || $i==count($_products)): ?>
        </ul>
        <?php endif ?>
    <?php endforeach; ?>
<?php endif; ?>