<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>

<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<?php echo $this->getParentBlock()->getParentBlock()->getChildHtml("breadcrumbs"); ?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view">
    <div class="product-essential">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>

        <div class="product-img-box">
            <?php if ($flashId = $_product->getProductFlash()) : ?>
                <?php $flash =  Mage::helper('attributeoptionimage')->getAttributeOptionImage($flashId); ?>
                <?php echo '<img class="corner-badge left" src="' . $flash . '" />'; ?>
            <?php endif; ?>
            <?php echo $this->getChildHtml('media') ?>
        </div>

        <div class="product-shop">
            <div class="product-name">
                <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
            </div>

            <h4>
                <a href="/<?php echo Mage::helper('brands/brands')->getBrandUrl($_product->getId()); ?>" class="more-from-brand">
                    see other <?php echo Mage::helper('brands/brands')->getBrand($_product->getId()); ?> products
                </a>
            </h4>

            <?php if ($_product->getShortDescription()):?>
                <div class="short-description">
                    <div class="std">
                        <p><?php echo $this->helper('cms')->getBlockTemplateProcessor()->filter($_product->getDescription()); ?></p>
                    </div>
                </div>
            <?php endif;?>

            <div class="short-description">
                <div class="std">
                    <p>Product Code: <?php echo $_product->getSku() ?></p>
                </div>
            </div>

            <?php echo $this->getChildHtml('alert_urls') ?>
            <?php echo $this->getChildHtml('product_type_data') ?>
            <?php echo $this->getChildHtml('currency-converter') ?>
            <?php echo $this->getTierPriceHtml() ?>
            <?php echo $this->getChildHtml('extrahint') ?>

            <?php if (!$this->hasOptions()):?>
                <div class="add-to-box">
                    <?php if($_product->isSaleable()): ?>
                        <?php echo $this->getChildHtml('addtocart') ?>
                    <?php endif; ?>
                </div>
                <?php //echo $this->getChildHtml('extra_buttons') ?>
            <?php else: ?>

            <?php if ($_product->isSaleable()): ?>
                <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
            <?php endif;?>

            <?php endif; ?>



            <?php echo $this->getChildHtml('other') ?>

            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php //echo $this->getChildChildHtml('container1', '', true, true) ?>
            <?php endif;?>
        </div>

        <div class="clearer"></div>
    </form>

    <script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
    </script>
    </div>

    <div class="product-collateral">

	<ul class="tabs">
            <li><a href="#box-description"><?php echo $this->__("Product Description") ?></a></li>
            <li><a href="#box-delivery"><?php echo $this->__("Delivery &amp; Returns") ?></a></li>
            <?php if ($_product->getSizingChart()): ?>
                <li><a href="#box-sizing"><?php echo $this->__("Sizing Chart") ?></a></li>
            <?php endif; ?>
	</ul>

	<div class="product-tabs">
            <div id="box-description" class="tab-content">
                <?php echo Mage::helper('rippleffect/formatting')->wrapInPTags($_product->getDescription()) ?>
            </div>
            <div id="box-delivery" class="tab-content">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('delivery_callout')->toHtml() ?>
            </div>
            <?php if ($_product->getSizingChart()): ?>
            <div id="box-sizing" class="tab-content">
                <?php
                $chart_code = strtolower($_product->getResource()->getAttribute('sizing_chart')->getSource()->getOptionText($_product->getSizingChart()));
                echo $this->getLayout()->createBlock('cms/block')->setBlockId('sizing_' . $chart_code)->toHtml();
                ?>
            </div>
            <?php endif; ?>
	</div>
    </div>

    <?php echo $this->getChildHtml('upsell_products') ?>

</div>
<script type="text/javascript">
    $jq(document).ready(function () {
        $jq(".tab-content").hide();
        $jq("ul.tabs li:first").addClass("active").show();
        $jq(".tab-content:first").show();

        $jq("ul.tabs li").click(function() {
            $jq("ul.tabs li").removeClass("active");
            $jq(this).addClass("active");
            $jq(".tab-content").hide();

            var activeTab = $jq(this).find("a").attr("href");
            $jq(activeTab).fadeIn();
            return false;
        });

        $jq('#product-gallery > img:first').addClass("zoom-active");
        $jq('#product-gallery > a').fancybox();

        $jq('.zoom-btn').bind('click', function() {
            var imId = $jq('.zoom-active').attr("id");
            $jq('#link-' + imId).click();
	});

        $jq('.more-views > a').each(function(){
            $jq(this).click(function(e){
                e.preventDefault();
                var rel = $jq(this).attr('rel');

                $jq('#product-gallery > img').each(function(){
                    $jq(this).removeClass("zoom-active").hide();
                });
                $jq('#' + rel).addClass("zoom-active").fadeIn();
            });
        });
    });
</script>
