<div class="block block-banner<?php if ($this->getClass()): ?> <?php echo $this->getClass() ?><?php endif; ?>">
    <a href="<?php echo $this->getLinkUrl() ?>" class="block-content">
    	<?php if ($this->getH2()): ?><h2><?php echo $this->__($this->getH2()) ?></h2><?php endif; ?>
	   	<?php if ($this->getH3()): ?><h3><?php echo $this->__($this->getH3()) ?></h3><?php endif; ?>
        <span>Click here to find out more</span>
    </a>
</div>