<div class="right-compare">
<?php if ($this->getH2()): ?><h2><?php echo $this->__($this->getH2()) ?></h2><?php endif; ?>

        <ul>
            <li>
                <a href="#" class="product-image"><img  src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/rippleffect/gold/images/structure/test-image.jpg" width="64" height="64" /></a>
                <h4><a href="#">Apple iMac 21.5"</a></h4>
				<h5>&pound;2999.00</h5>
                <button type="button" title="<?php echo $this->__('View Product') ?>" class="button small-default-btn"><span><span><?php echo $this->__('View Product') ?></span></span></button>
            </li>
            
            <li>
                <a href="#" class="product-image"><img  src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/rippleffect/gold/images/structure/test-image.jpg" width="64" height="64" /></a>
                <h4><a href="#">Apple iMac 21.5"</a></h4>
				<h5>&pound;2999.00</h5>
                <button type="button" title="<?php echo $this->__('View Product') ?>" class="button small-default-btn"><span><span><?php echo $this->__('View Product') ?></span></span></button>
            </li>

            <li>
                <a href="#" class="product-image"><img  src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/rippleffect/gold/images/structure/test-image.jpg" width="64" height="64" /></a>
                <h4><a href="#">Apple iMac 21.5"</a></h4>
				<h5>&pound;2999.00</h5>
                <button type="button" title="<?php echo $this->__('View Product') ?>" class="button small-default-btn"><span><span><?php echo $this->__('View Product') ?></span></span></button>
            </li>
        </ul>

    
    <div class="block block-banner block_free_delivery">
    <a class="block-content" href="free_delivery">
    	<h2>Free UK Delivery</h2>
        <h3>On purchases over £500</h3>
        <span>Click here to find out more</span>
    </a>
	</div>
    
</div>
