<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Jamie Murphy
 */
?>
<div class="page-title blog-title <?php if (!$this->isFirstPage()): ?>not-<?php endif; ?>first-page<?php if ($this->isFirstPage() && $this->getTagLine()): ?> with-tagline<?php endif; ?>">
    <h1><?php echo $this->escapeHtml($this->getTagline()) ?></h1>
</div>
<div class="blog-home">
    <?php echo $this->getPostListHtml() ?>
</div>
