<?php

$installer = $this;

$connection = $installer->getConnection();

$installer->startSetup();

$roles = array();
$roles["bronze"] = array(
    "admin/catalog" => true,
    "admin/catalog/categories" => true,
    "admin/catalog/products" => true,
    "admin/catalog/search" => true,
    "admin/cms" => true,
    "admin/cms/block" => true,
    "admin/cms/media_gallery" => true,
    "admin/cms/page" => true,
    "admin/cms/page/delete" => true,
    "admin/cms/page/save" => true,
    "admin/customer" => true,
    "admin/customer/group" => true,
    "admin/customer/manage" => true,
    "admin/customer/online" => true,
    "admin/dashboard" => true,
    "admin/sales" => true,
    "admin/sales/checkoutagreement" => true,
    "admin/sales/creditmemo" => true,
    "admin/sales/invoice" => true,
    "admin/sales/order" => true,
    "admin/sales/order/actions" => true,
    "admin/sales/order/actions/cancel" => true,
    "admin/sales/order/actions/capture" => true,
    "admin/sales/order/actions/comment" => true,
    "admin/sales/order/actions/create" => true,
    "admin/sales/order/actions/creditmemo" => true,
    "admin/sales/order/actions/edit" => true,
    "admin/sales/order/actions/email" => true,
    "admin/sales/order/actions/emails" => true,
    "admin/sales/order/actions/hold" => true,
    "admin/sales/order/actions/invoice" => true,
    "admin/sales/order/actions/reorder" => true,
    "admin/sales/order/actions/review_payment" => true,
    "admin/sales/order/actions/ship" => true,
    "admin/sales/order/actions/unhold" => true,
    "admin/sales/order/actions/view" => true,
    "admin/sales/shipment" => true,
    "admin/sales/tax" => true,
    "admin/sales/tax/rates" => true,
    "admin/system" => true,
    "admin/system/config" => true,
    "admin/system/config/contacts" => true,
    "admin/system/config/trans_email" => true,
    "admin/system/myaccount" => true,
);
$roles["silver"] = array_merge($roles['bronze'], array(
    "admin/catalog/reviews_ratings" => true,
    "admin/catalog/reviews_ratings/ratings" => true,
    "admin/catalog/reviews_ratings/reviews" => true,
    "admin/catalog/reviews_ratings/reviews/all" => true,
    "admin/catalog/reviews_ratings/reviews/pending" => true,
    "admin/catalog/sitemap" => true,
    "admin/newsletter" => true,
    "admin/newsletter/subscriber" => true,
    "admin/promo" => true,
    "admin/promo/catalog" => true,
    "admin/promo/quote" => true,
    "admin/report" => true,
    "admin/report/customers" => true,
    "admin/report/customers/accounts" => true,
    "admin/report/customers/orders" => true,
    "admin/report/customers/totals" => true,
    "admin/report/products" => true,
    "admin/report/products/downloads" => true,
    "admin/report/products/lowstock" => true,
    "admin/report/products/ordered" => true,
    "admin/report/products/sold" => true,
    "admin/report/products/viewed" => true,
    "admin/report/review" => true,
    "admin/report/review/customer" => true,
    "admin/report/review/product" => true,
    "admin/report/salesroot" => true,
    "admin/report/salesroot/coupons" => true,
    "admin/report/salesroot/invoiced" => true,
    "admin/report/salesroot/paypal_settlement_reports" => true,
    "admin/report/salesroot/paypal_settlement_reports/fetch" => true,
    "admin/report/salesroot/paypal_settlement_reports/view" => true,
    "admin/report/salesroot/refunded" => true,
    "admin/report/salesroot/sales" => true,
    "admin/report/salesroot/shipping" => true,
    "admin/report/salesroot/tax" => true,
    "admin/report/search" => true,
    "admin/report/shopcart" => true,
    "admin/report/shopcart/abandoned" => true,
    "admin/report/shopcart/product" => true,
    "admin/report/statistics" => true,
));
$roles["gold"] = array_merge($roles['silver'], array(
    "admin/cms/poll" => true,
    "admin/newsletter" => true,
    "admin/newsletter/problem" => true,
    "admin/newsletter/queue" => true,
    "admin/newsletter/subscriber" => true,
    "admin/newsletter/template" => true,
));

Mage::getModel('rippleffect/roles_installer')->installRoles($roles);

$installer->endSetup();
