<?php

    $isDisplayed = $this->isDisplayed();
    if($isDisplayed) {
        $url = $this->getPopupUrl();
        $img = '/media/jjm/sitepopup/' . $this->getPopupImage(); ?>

        <div id="site-popup" class="site-popup">

            <?php if(strlen($url) > 0) { ?>
                <a href="<?php echo $url; ?>">
                    <img src="<?php echo $img; ?>" />
                </a>
            <?php } else { ?>
                <img src="<?php echo $img; ?>" />
            <?php } ?>

            <?php echo $this->getChildHtml('popup.newsletter'); ?>
        </div>

    <?php } ?>

