<?php

    $isDisplayed = $this->isDisplayed();
    if($isDisplayed) {
        $url = $this->getPopupUrl();
        $img = '/media/' . $this->getPopupImage(); ?>

        <div id="site-popup" class="site-popup">

            <a href="<?php echo $url; ?>">
                <img src="<?php echo $img; ?>" />
            </a>

            <?php echo $this->getChildHtml('popup.newsletter'); ?>
        </div>

    <?php } ?>

