<?php
/**
 * Product:     Shop By Brands
 * Package:     Aitoc_Aitmanufacturers_3.1.6_374174
 * Purchase ID: tVvdGs19UDRv1nt8kXtoMgj1k0nJnuQXyRfYV0sM51
 * Generated:   2012-09-26 12:38:30
 * File path:   app/design/adminhtml/default/default/template/aitmanufacturers/attribute/edit.phtml
 * Copyright:   (c) 2012 AITOC, Inc.
 */
?>
<?php

$switcher = $this->getChild('attribute_store_switch');
echo $switcher->toHtml();
if ($values = $this->getFormValues('default', 0))
{
    echo $this->getForm()->setValues($values)->toHtml();
}
else
{
    echo $this->getForm()->toHtml();
}

if (!Mage::app()->isSingleStoreMode())
{
    $_websiteCollection = $switcher->getWebsiteCollection();
    foreach ($_websiteCollection as $_website)
    {
        if ($values = $this->getFormValues('website', $_website->getId()))
        {
            echo $this->getBlankForm('website', $_website->getId())->setValues($values)->toHtml();
        }
        else
        {
            echo $this->getBlankForm('website', $_website->getId())->toHtml();
        }
        foreach ($switcher->getGroupCollection($_website) as $_group)
        {
             foreach ($switcher->getStoreCollection($_group) as $_store)
             {
                if ($values = $this->getFormValues('store', $_store->getId()))
                {
                    echo $this->getBlankForm('store', $_store->getId())->setValues($values)->toHtml();
                }
                else
                {
                    echo $this->getBlankForm('store', $_store->getId())->toHtml();
                }
            }
        }
    }
}

?>