<?php if(count($this->getItemCollection()->getItems())): ?>
<div class="box-collateral box-up-sell">
    <h2><?php echo $this->__('You may also be interested in...') ?></h2>
    <div class="products-grid" id="upsell-product-table">
    <?php // $this->setColumnCount(5); // uncomment this line if you want to have another number of columns. also can be changed in layout ?>
    <?php $this->resetItemsIterator() ?>
    <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
        <ul>
        <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
            <?php if($_link=$this->getIterableItem()): ?>
            <li class="<?php if ($_j == ($this->getColumnCount() - 1)): ?>last<?php elseif ($_j == 0): ?>first<?php endif; ?>">
                <a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(125) ?>" width="125" height="125" alt="<?php echo $this->htmlEscape($_link->getName()) ?>" /></a>
                <h2 class="product-name"><a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>"><?php echo $this->htmlEscape($_link->getName()) ?></a></h2>
                <?php echo $this->getPriceHtml($_link, true, '-upsell') ?>
                
                <div class="actions">
                    <?php if($_link->isSaleable()): ?>
                        <a class="read-more" href="<?php echo $_link->getProductUrl() ?>"><?php echo $this->__("View Details") ?></a>
                        <!--<a class="buy-now" href="<?php echo $this->getAddToCartUrl($_link) ?>"><?php echo $this->__("Add To Bag") ?></a>-->
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                </div>
<!--                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_link) ?>')"><span><span><?php echo $this->__('Buy Now') ?></span></span></button>-->
            </li>
            <?php else: ?>
            <li class="empty">&nbsp;</li>
            <?php endif; ?>
        <?php endfor; ?>
        </ul>
    <?php endfor; ?>
    </div>
</div>
<?php endif ?>
<script type="text/javascript">
$jq = jQuery.noConflict();
    $jq(document).ready(function (){
    	$jq('#upsell-product-table li:last-child').css('margin','0');
    });
</script>
