<?php echo $this->getChildHtml('messages'); ?>
<?php echo $this->getChildHtml('breadcrumbs'); ?>


    <div class="style-guides">
        <?php foreach($this->_entities as $entity) : ?>

            <div class="guide">
                <a href="/styleguides/celebrity?name=<?php echo $entity->getName(); ?>">
                    <img src="/media/<?php echo $entity->getImage1(); ?>" alt="<?php echo $entity->getName(); ?>" />
                    <p><?php echo $entity->getName(); ?></p>
                    <div class="button"><?php echo $this->__('View this style'); ?></div>
                </a>

            </div>

        <?php endforeach; ?>
    </div>

<?php echo $this->getChildHtml('pager'); ?>

<script type="text/javascript">
    jQuery(document).ready(function($) {
        $('a').on('click', function(e) {
            e.preventDefault();
            console.log(e.currentTarget.href);
            window.location.href = e.currentTarget.href;
        })
    })
</script>