<div class="footer-links clearfix">
	<div class="footer-social">
    	<a class="footer-twitter" href="http://twitter.com/kidscavern"></a>
        <a class="footer-facebook" href="http://www.facebook.com/kidscavern"></a>
        <a class="footer-email" href="<?php echo Mage::getUrl('contacts') ?>"></a>
    </div><!--//end of footer social-->

    <div class="footer-col">
    	<h2>CUSTOMER SERVICES</h2>
        <ul>
            <li><a href="<?php echo Mage::getUrl('about-kids-cavern') ?>">About Us</a></li>
            <li><a href="http://kidscavern.wordpress.com/">Blog</a></li>
            <li><a href="<?php echo Mage::getUrl('customer/account/create/') ?>">Newsletter Signup</a></li>
        </ul>
        <ul>
            <li><a href="<?php echo Mage::getUrl('terms-and-conditions') ?>">Terms &amp; Conditions</a></li>
            <li><a href="<?php echo Mage::getUrl('returns-policy') ?>">Returns Policy</a></li>
            <li><a href="<?php echo Mage::getUrl('delivery') ?>">Delivery</a></li>
        </ul>
    </div><!--//end of footer col -->

    <div class="footer-col">
    	<h2>HERE TO HELP</h2>
        <ul>
            <li><a href="<?php echo Mage::getUrl('catalog/seo_sitemap/category') ?>">Sitemap</a></li>
            <li><a href="<?php echo Mage::getUrl('privacy-policy') ?>">Privacy Policy</a></li>
            <li><a href="<?php echo Mage::getUrl('contacts') ?>">Contact Us</a></li>
        </ul>
        <ul>
            <li><a href="<?php echo Mage::getUrl('kids-cavern-loyalty-points') ?>">Kids Cavern Loyalty Points</a></li>
            <li><a href="<?php echo Mage::getUrl('cookie-policy') ?>">Cookie Policy</a></li>
        </ul>
    </div><!--//end of footer col -->

</div>

<div class="footer">
	<div class="footerInner">
        <p>Kids Cavern, 22 Cavern Walks, Mathew Street, Liverpool L2 6 RE, England</p>
        <p class="tel">+44 (0)151 236 1475</p>
        <p class="fax">+44 (0)151 236 5396</p>


        <div class="trustpilot">
            <div class="tp_-_category-badge" data-tp-settings="domainId:1030959,size:100">
                <a href="http://www.trustpilot.co.uk/review/www.kidscavern.co.uk" hidden>Kids Cavern Reviews</a>
            </div>
            <script type="text/javascript">
              (function(){var a="https:"==document.location.protocol?"https://ssl.trustpilot.com":"http://s.trustpilot.com",b=document.createElement("script");b.type="text/javascript";b.async=true;b.src=a+"/tpelements/tp_elements_all.js";var c=document.getElementsByTagName("script")[0];c.parentNode.insertBefore(b,c)})();
            </script>
        </div>

        <p class="payment-logos">We accept the following payment mothods: Visa Debit, Visa Credit, Visa Electron and Mastercard</p>
    </div>
</div>
